### ISSUE TITLE
Yield equivalent

### ISSUE THREAD

**Issue by thomasfredericks** [SofaPirate/Plaquette#11]
Arduino for ESP8266 has a special function called ```yield()```. 

The ESP8266 must use the main thread to process WiFi paquets. By default, the code does this between calls to ```loop()```. But if the user requires some code that locks the main process, the user can make calls to ```yield()``` so that the ESP8266 does the behind the scene stuff.

Something similar for Plaquette would be very helpful for compatibility with third party libraries.

Note that Arduino for ESP8266's ```delay()``` integrates the ```yield()``` function so that ```delay()``` does not lock-up the WiFi.

**Comment by sofian** [comment]
Do you suggest for example that we call ```yield()``` in Plaquette.update() on ESP8266-ESP32 such that if there is a lot of things to process then we do not block the process?

**Comment by thomasfredericks** [comment]
```yield()``` is automatically called by ```loop()``` in Arduino for ESP8266. Therefore Plaquette already calls it.

I do not think the ESP32 needs a ```yield()``` because it has a separate processor to manage the WiFi and Bluetooth network.

I am suggesting a ```Plaquette.yield()``` so that Plaquette's internal private ```step()``` can be called from elsewhere.

**Comment by sofian** [comment]
So the yield() would essentially call step()?

**Comment by thomasfredericks** [comment]
Not step() but the internal step() i.e. ```Plaquette::update();```

**Comment by thomasfredericks** [comment]
In a way, to make Plaquette::update() public.

**Comment by sofian** [comment]
So one would call it using ```Plaquette::update()``` ? Wouldn't it be nicer to have some kind of a global function like on the ESP8266 (however ```yield()``` is already taken so we should use something else)?

**Comment by thomasfredericks** [comment]
> So one would call it using Plaquette::update() ?

yes


>  Wouldn't it be nicer to have some kind of a global function like on the ESP8266 (however yield() is already taken so we should use something else)?

yes, but not sure I would make it global as it is an advanced feature.

**Comment by sofian** [comment]
In fact ```Plaquette::update()``` _is_ public so you can already use it like you are intending to.

**Comment by thomasfredericks** [comment]
Ok. I did notice that. As long as it stays in the public API.
