### ISSUE TITLE
Make the StreamIn non-blocking

### ISSUE THREAD

**Issue by sofian** [SofaPirate/Plaquette#3]
StreamIn::update() uses parseFloat() which is blocking. Make it non-blocking.

**Comment by sofian** [comment]
@thomasfredericks Did you have code for this somewhere?

**Comment by thomasfredericks** [comment]
Just AsciiMassage :P

**Comment by sofian** [comment]
I implemented something that seems to be working: 852fe3b2fd2cd9a35844de3c4fa207a568b98752 (I have tested it).

**Comment by sofian** [comment]
Closed by 852fe3b2fd2cd9a35844de3c4fa207a568b98752
