### ISSUE TITLE
Rename AnalogOut

### ISSUE THREAD

**Issue by thomasfredericks** [SofaPirate/Plaquette#34]
`AnalogOut` is a misnomer. It should be `PWMOut` or `PwmOut`. The `Pq_05_AnalogOut` example even states the misnomer in its comments:

>  * Demonstrates analog (PWM) output by sending a ramping value into a LED output
>  * connected to PWM pin 9.

This misnomer has been carried from Wiring to Arduino and is confusing, counter intuitive, does not help beginners and conflicts with futur developments. For example, the same pins can do PWM and DAC (real analog out) on the ESP32. See pins 14 and 15: https://hackadaycom.files.wordpress.com/2016/09/pinout_wroom_pinout.png

**Comment by sofian** [comment]
I know and we had that discussion before and we chose to stick with AnalogOut which focuses on the concept (of a "continuous" data - analog - as opposed to a "binary" data - digital). I would be ready to open the debate again but I think it there are advantages and disadvantages to both approaches.

**Comment by sofian** [comment]
I think when we are talking in terms of low-frequency data signals (control) that is the target of Plaquette, the difference between a real DAC and PWM is quite irrelevant. But it is true that there are situations that make it relevant - especially for most advanced applications. In my own experience it has rarely made a difference to use PWM as opposed to DAC except in rare circumstances using hi-frequency signals (ie. sound). But we already agreed that sound was not on the horizon for the moment for Plaquette.

**Comment by sofian** [comment]
I think the abstract concept of "analog" vs "digital" is easy to understand and works in 90% of the cases, which is what motivated to keep these names in the core classes. So even though I do not think this nomenclature is optimal - they do not represent what truly happens "under the hood"; and also it would be more accurate for example to use the words "percentage" and "binary" or "continuous" and "discrete" - they are more evocative (ie. people quickly understand the difference) to both (a) users with no knowledge / experience with hardware (b) users with experience with Arduino.

The other issue I have with changing the name is that, once again, this would break with our current documentation, especially the upcoming set of basic videos. This is not a reason not to change, but it is a good reason to take more time to think it through - like I said we already had that discussion in the past.

**Comment by thomasfredericks** [comment]
> of a "continuous" data - analog - as opposed to a "binary" data - digital)

Exactly. PWM is **not** "continuous" data. It only seems that way because PWM is too fast for human perception when connected to a LED. **PWM != "continuous" data**. At slower rates (60hz) it becomes very clear that PWM is a square **digital** wave. The only reason that people confuse PWM with analog is because of the initial documentation error in _Wiring_. 

The difference with  DAC and PWM is extremely relevant. I come across this issue often in my basic circuitry. It is also an important distinction in motor control. If you connect a PWM output to an analog inpout you **will not** get the expected result. The only time it is not an issue is in the single case of a LED. 

The only reason PWM is confused with analog out is because of the misnomer. They have nothing in common. For real! 

I think that the work to fix this is documentation right now will be a lot less trouble than fixing all the problems this will cause downstream.

**Comment by thomasfredericks** [comment]
Some sensors do output real analog output (sharp infrared distance sensors). It becomes confusing when the term used in the documentation does not represent what these sensors send. For example:

- sharp infrared distance sensor -> analog in 👍 
- arduino "analog out" -> analog in 👎 (does not work)

**Comment by sofian** [comment]
> Exactly. PWM is not "continuous" data. It only seems that way because PWM is too fast for human perception when connected to a LED.

But isn't it true also for other electronic components? Really, just LEDs can be controlled accurately by PWM?
I mean, for servos, we have a separate set of objects (ServoOut) that use the Servo library.

The analog-out-to-analog-in incompatibility is a good argument as a demonstration, although I have never even tried to do something like this.

It looks like mbed has chosen that path: https://docs.mbed.com/docs/mbed-os-api-reference/en/latest/APIs/io/inputs_outputs/
Indeed their PwmOut object allows the user to adjust the frequency of the PWM as well as the duty cycle.

Anyway, let's think about this more. It would be good to involve other people in the discussion as well.

**Comment by thomasfredericks** [comment]
`But isn't it true also for other electronic components? Really, just LEDs can be controlled accurately by PWM?`

No it is not true for other electronic components. It only works for LED because of human perception. Electronic components go much faster.

Servos use a particular PWM at 50 hz  with a pulse width that varies between 5% and 10%. 

To use the term analog output to control DC motors is confusing. It makes people think that DC motor speed is controlled by varying the voltage which is false. They are controlled by pulsating a fixed voltage.

**Comment by sofian** [comment]
What I would do is to create the PwmOut and make it the "new standard". However, for now I would keep the AnalogOut backwards-compatible (at least until the release of, say, Plaquette 2.0). We could say that it is deprecated to use AnalogOut for PWM control but it would still work on Arduino platforms that don't have DAC support.

One issue I see is that the ESP32 does not support PWM "natively" but it has two ways to do it using the SigmaDelta and the LEDc. So I am not sure what to do with those. It looks like the LEDc can be easily "wrapped" as a PWM (https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/PWM.h) so I guess this would be the right approach.

Yet the problem will arise in the examples, because we might have to have different settings / names / pin numbers for the different platforms (AVR, ESP, Teensy).

**Comment by thomasfredericks** [comment]
Once development settles down for the ESP32 we will figure it out (I believe the community is trying to settle the mess with the _analog out_ name also). I recommend to simply not let it compile for the ESP32.

Here is another example of an implementation that uses the analog out term properly:
* https://learn.adafruit.com/circuitpython-essentials/circuitpython-analog-out
* https://learn.adafruit.com/circuitpython-essentials/circuitpython-pwm

**Comment by sofian** [comment]
Also see this: http://librambutan.readthedocs.io/en/latest/lang/api/pwmwrite.html
They write: "The Arduino function analogWrite() is an alias for pwmWrite(), but it is badly named, and its use is discouraged."

**Comment by sofian** [comment]
Well currently on ESP32 AnalogOut compiles and it does the right thing (ie. it calls dacWrite, cause analogWrite does not exist on the ESP32 anyway). So we do not need to change anything for now. However we should introduce a new class called PwmOut.

**Comment by sofian** [comment]
@thomasfredericks I recommend you close this issue for now as I believe #35 will solve it. But since you opened the bug it should be your call to keep it open or close it.
